# Generated by Django 4.1.5 on 2023-06-05 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_account_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='otp',
            new_name='pin',
        ),
    ]
