# Generated by Django 4.1.5 on 2023-06-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='beneficiary',
        ),
        migrations.AddField(
            model_name='payment',
            name='beneficiary_account_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
