# Generated by Django 4.1.5 on 2023-06-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_paymentlink_remove_paymentlinks_basepayment_ptr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlink',
            name='link_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
