# Generated by Django 4.1.5 on 2023-06-09 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_paymentlink_link_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='beneficiary_username',
            new_name='beneficiary',
        ),
    ]
