# Generated by Django 4.1.5 on 2023-06-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_payment_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.CharField(default='NGN', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='paystack_payment_reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
