# Generated by Django 4.1.5 on 2023-07-14 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_rename_beneficiary_username_transaction_beneficiary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_number',
        ),
    ]
