# Generated by Django 4.1.5 on 2023-07-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_remove_account_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(blank=True, default='NGN', max_length=50, null=True),
        ),
    ]
