# Generated by Django 4.1.5 on 2023-06-08 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_basepayment_paymentlinks_paymentqrcode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentrequest',
            old_name='user',
            new_name='sender',
        ),
    ]
