# Generated by Django 4.1.5 on 2023-06-08 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_rename_user_paymentrequest_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrequest',
            name='id',
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='uid',
            field=models.UUIDField(default=1, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
