# Generated by Django 4.1.5 on 2023-06-08 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_remove_paymentrequest_id_paymentrequest_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='uid',
            field=models.UUIDField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
