# Generated by Django 4.1.5 on 2023-06-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0012_alter_paymentrequest_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='recipient',
            field=models.CharField(max_length=100),
        ),
    ]
