# Generated by Django 4.1.5 on 2023-06-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0013_alter_paymentrequest_recipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='beneficiary_account_number',
        ),
        migrations.AddField(
            model_name='payment',
            name='beneficiary_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
